### ISSUE TITLE
DatabaseError: file is not a database

### ISSUE THREAD

**Issue by xvybihal** [adiov/authplus-to-andotp-magiculator#1]
Thanks for this project, I am glad I found it and appreciate the work!

Unfortunately, I am not able to read the database file freshly exported from Authenticator Plus (beta).

```
./authplus-to-andotp.py -d authplus.db -o auth.json
Authenticator Plus master password: 
Traceback (most recent call last):
  File "./authplus-to-andotp.py", line 29, in <module>
    cur.execute("SELECT * FROM accounts ORDER BY position ASC")
pysqlcipher3.dbapi2.DatabaseError: file is not a database
```

**Comment by xvybihal** [comment]
I found the reason causing this.

Authenticator Plus is using version 3 settings of `sqlcipher`. The version 4 changed those: https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/

Setting [default compatibility level](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_default_compatibility) to 3 allows me to read the db correctly and exports .json.

**Comment by adiov** [comment]
Well done debugging it and finding a solution!

**Comment by abbaspour** [comment]
For me, `cipher_default_compatibility` was not enough. `PRAGMA cipher_compatibility = 3` however did work.

**Comment by adiov** [comment]
After testing both, it seems `cipher_compatibility` is indeed more reliable. As far as I can tell from [the documentation, `cipher_default_compatibility`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_default_compatibility) applies the compatibility setting for connections opened _after_ the `PRAGMA` statement is issued, while `cipher_compatibility` applies it for the currently open connection. I believe the latter is needed behaviour here.

I've modified it to use `cipher_compatibility` now. Thanks @abbaspour!

**Comment by terinjokes** [comment]
Even with this change, and manually setting the SQLCipher3 backwards compatibility settings, I still get this error.

**Comment by terinjokes** [comment]
I edited my virtualenv to link against sqlcipher 3.4.2 and it worked fine. I'm not sure why setting `cipher_compatibility` wasn't working in `sqlcipher 4.4.0`.

**Comment by adiov** [comment]
That is quite odd. I wonder if a more robust solution would be to dockerise it and explicitly include the 3.4.2 version in the image.

**Comment by terinjokes** [comment]
That might be easiest, especially since most users are going to use this script once and then never again.

**Comment by smartiq** [comment]
Hello.  Just hit this issue trying to Migrate AuthPlus->andOTP (Running bf0786a).  I tried many things to get around the "file is not a database" error.  I also starting using sqlcipher directly and had the same issues there ("file is not a database").  I tried all combinations of cipher_compatibility from 1..3.  None worked in neither sqlcipher nor authplus-to-andotp-magiculator.  I tried changing the master password in Authenticator Plus and re-exporting to see if it was a character set issue or something, but nothing worked with the vanilla workflow.

The only way I eventually got it to work was to:
sqlcipher authplus.db
PRAGMA key = '<>';
PRAGMA cipher_migrate;
SELECT * FROM accounts ORDER BY position ASC;

At his point I got valid row data.

I then remarked the "PRAGMA cipher_compatibility = 3" line from the python script, ran it again, and got a usable JSON file.

Little bit of a hassle, but still super glad this script exists as it saved me a ton of time.

For the record, I was running "SQLite version 3.33.0 2020-08-14 13:23:32 (SQLCipher 4.4.1 community)"

Perhaps adding a flag "--upgrade-db" or something that ran the PRAGMA cipher_migrate would be advantageous.  It smells like an upstream cipher_compatibility issue.

**Comment by adiov** [comment]
Would it make sense to detect the local SQLCipher version and issue the appropriate PRAGMA statements based on that? Perhaps I can have a separate function that attempts some of the above hacks until the DB becomes readable.

**Comment by terinjokes** [comment]
Packaging in Docker sounds even more appealing, as you'll know what version of sqlcipher is being used.

**Comment by adiov** [comment]
This was convincing enough to offer a Docker option. I have PR #4, feel free to review and/or test.
