### ISSUE TITLE
support Battle.net tokens

### ISSUE THREAD

**Issue by terinjokes** [adiov/authplus-to-andotp-magiculator#3]
> As far as I can tell, Authenticator Plus doesn't handle checksum algorithms other than SHA-1 or OTP digits other than 6. The output file will use those values by default.

Authenticator Plus supports Battle.net tokens, which are 8 digits long (but still 30s SHA-1). These can be identify by being "type `2` in the accounts table, and `secret` is hex encoded instead of base32.

**Comment by adiov** [comment]
I added support for it with bf0786a.
